USE [master]
GO

/****** Object:  Database [SignatureSvc]    Script Date: 5/14/2018 11:58:36 AM ******/
CREATE DATABASE [SignatureSvc]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SignatureSvc', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\SignatureSvc.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SignatureSvc_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\SignatureSvc_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [SignatureSvc] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SignatureSvc].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SignatureSvc] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SignatureSvc] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SignatureSvc] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SignatureSvc] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SignatureSvc] SET ARITHABORT OFF 
GO

ALTER DATABASE [SignatureSvc] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SignatureSvc] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SignatureSvc] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SignatureSvc] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SignatureSvc] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SignatureSvc] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SignatureSvc] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SignatureSvc] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SignatureSvc] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SignatureSvc] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SignatureSvc] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SignatureSvc] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SignatureSvc] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SignatureSvc] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SignatureSvc] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SignatureSvc] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SignatureSvc] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SignatureSvc] SET RECOVERY FULL 
GO

ALTER DATABASE [SignatureSvc] SET  MULTI_USER 
GO

ALTER DATABASE [SignatureSvc] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SignatureSvc] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SignatureSvc] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SignatureSvc] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SignatureSvc] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SignatureSvc] SET QUERY_STORE = OFF
GO

USE [SignatureSvc]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [SignatureSvc] SET  READ_WRITE 
GO


